/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as SignInImport } from './routes/sign-in'
import { Route as IndexImport } from './routes/index'
import { Route as MentorsIndexImport } from './routes/mentors/index'
import { Route as ChatIndexImport } from './routes/chat/index'
import { Route as MentorsIdImport } from './routes/mentors/$id'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MentorsIndexRoute = MentorsIndexImport.update({
  id: '/mentors/',
  path: '/mentors/',
  getParentRoute: () => rootRoute,
} as any)

const ChatIndexRoute = ChatIndexImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRoute,
} as any)

const MentorsIdRoute = MentorsIdImport.update({
  id: '/mentors/$id',
  path: '/mentors/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/mentors/$id': {
      id: '/mentors/$id'
      path: '/mentors/$id'
      fullPath: '/mentors/$id'
      preLoaderRoute: typeof MentorsIdImport
      parentRoute: typeof rootRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatIndexImport
      parentRoute: typeof rootRoute
    }
    '/mentors/': {
      id: '/mentors/'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/mentors/$id': typeof MentorsIdRoute
  '/chat': typeof ChatIndexRoute
  '/mentors': typeof MentorsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/mentors/$id': typeof MentorsIdRoute
  '/chat': typeof ChatIndexRoute
  '/mentors': typeof MentorsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/mentors/$id': typeof MentorsIdRoute
  '/chat/': typeof ChatIndexRoute
  '/mentors/': typeof MentorsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/mentors/$id'
    | '/chat'
    | '/mentors'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/sign-up' | '/mentors/$id' | '/chat' | '/mentors'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/mentors/$id'
    | '/chat/'
    | '/mentors/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  MentorsIdRoute: typeof MentorsIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
  MentorsIndexRoute: typeof MentorsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  MentorsIdRoute: MentorsIdRoute,
  ChatIndexRoute: ChatIndexRoute,
  MentorsIndexRoute: MentorsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/sign-in",
        "/sign-up",
        "/mentors/$id",
        "/chat/",
        "/mentors/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    },
    "/mentors/$id": {
      "filePath": "mentors/$id.tsx"
    },
    "/chat/": {
      "filePath": "chat/index.tsx"
    },
    "/mentors/": {
      "filePath": "mentors/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
